openapi: 3.0.0
info:
  title: Kanban API
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
paths:
  /auth/register:
    post:
      summary: Register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                name: { type: string }
                email: { type: string }
                password: { type: string }
      responses:
        "201": { description: JWT issued }
  /auth/login:
    post:
      summary: Login
      responses:
        "200": { description: JWT issued }
  /boards:
    get:
      summary: List boards
      security: [{ bearerAuth: [] }]
      responses: { "200": { description: OK } }
    post:
      summary: Create board
      security: [{ bearerAuth: [] }]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                title: { type: string }
                description: { type: string }
                visibility: { $ref: "#/components/schemas/Visibility" }
      responses:
        "201": { description: Created }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Visibility:
      type: string
      enum: [private, team, public]
